server:
  port: 3031
spring:
  application:
    name: zeus-auth
  cloud:
    nacos:
      discovery:
        server-addr: resource.leons-tokyo.top:8848
        username: ${zeus.nacos.username}
        password: ${zeus.nacos.password}
        group: zeus
